### ISSUE TITLE
The demo project will eat lots of memory up to 1.5G+

### ISSUE THREAD

**Issue by xieweizhi** [litoarias/HACClusterMapViewController#1]
When I run the demo project, zoom in and scroll , the app wouldn't response anymore.

Here's the screenshot

![](https://cloud.githubusercontent.com/assets/1779863/9570838/dd87ef6c-4fc6-11e5-8425-f978f11bd995.png)

**Comment by litoarias** [comment]
You can try with the new update.
The most effective solution to meeting time to solve the excess memory is the map rotation lock.
If you find an alternative or more elegant solution as it requires the rotation of the map, you can contribute.

**Comment by ClarkXP** [comment]
the issue is present yet in code example
