### ISSUE TITLE
Problem using with swift

### ISSUE THREAD

**Issue by ghost** [litoarias/HACClusterMapViewController#11]
I do not know how to describe this, but what happen is, I cannot get cluster to show up, so I decide to debug and wha happen is that it cannot get any value in Line 21 and 22. please check the photo
![screen shot 2016-06-06 at 11 14 06 am](https://cloud.githubusercontent.com/assets/10571492/15811870/3c422624-2bd8-11e6-9990-367b6c94bac5.png)

**Comment by pomarec** [comment]
I don't have this problem with swift 3
