### ISSUE TITLE
didDeselectAnnotationView not working when using cocoapods

### ISSUE THREAD

**Issue by ranhsd** [litoarias/HACClusterMapViewController#12]
Hi , 
I added this library into my project via cocoapods pod 'HACClusterMapViewController' but from some reason i get a version where didDeselectAnnotationView is not working.. 
i investigated it a bit and found that the following line of code: 
`if ([view isKindOfClass:[HAClusterAnnotation class]]){`
need to be replaced with 
`if ([view.annotation isKindOfClass:[HAClusterAnnotation class]]){`

a **temporary** workaround (for those who want to use cocoapods) is to put the following line in your podfile 
`pod 'HACClusterMapViewController' , :git => 'https://github.com/litoarias/HACClusterMapViewController.git'`

Thanks,
Ran.

**Comment by litoarias** [comment]
Hi @ranhsd,
Thanks for this comment, I forgot to update the project Cocoacontrols.
You already have updated to use the Pod. ; D

**Comment by ranhsd** [comment]
Thanks a lot .. will change my podfile .. 

Ran.
