### ISSUE TITLE
app crashes if the data is not loaded in viewDidLoad

### ISSUE THREAD

**Issue by das-palash-appsbee** [litoarias/HACClusterMapViewController#13]
the app crashes if I use 

```
NSArray *data = @[
                      @{kLatitude:@48.47352, kLongitude:@3.87426,  kTitle : @"Title 1", kSubtitle : @"",            kIndex : @0},
                      @{kLatitude:@52.59758, kLongitude:@-1.93061, kTitle : @"Title 2", kSubtitle : @"Subtitle 2",  kIndex : @1},
                      @{kLatitude:@48.41370, kLongitude:@3.43531,  kTitle : @"Title 3", kSubtitle : @"Subtitle 3",  kIndex : @2},
                      @{kLatitude:@48.31921, kLongitude:@18.10184, kTitle : @"Title 4", kSubtitle : @"Subtitle 4",  kIndex : @3}];

    [self.mapView.coordinateQuadTree buildTreeWithArray:data];
```

other than viewDidLoad and viewWillAppear. I  have declared it in viewDidAppear and I got EXC_BAD_ACCESS on this line `if (!HACBoundingBoxIntersectsBoundingBox(node->boundingBox, range))` in `void HACQuadTreeGatherDataInRange(HACQuadTreeNode* node, HACBoundingBox range, HACDataReturnBlock block)` method. 
Now in my case I need to insert data in buildTreeWithArray after I get my current location. So thats not happening here. This method getting fired before annotation data initalization `- (void)mapView:(MKMapView *)mapView regionDidChangeAnimated:(BOOL)animated`. Please fix this.

`

**Comment by litoarias** [comment]
Thank you for contacting the incidence.
I solved the problem, you can try it anytime. 🎯

**Comment by das-palash-appsbee** [comment]
Thanks!!!
