### ISSUE TITLE
Clustering issue

### ISSUE THREAD

**Issue by palash89** [litoarias/HACClusterMapViewController#15]
Individual pins are not showing up when the coordinates are too near and zoomed into maximum level, instead showing cluster count.

I know it was posted earlier as an issue by **phaneendrakv** and also closed. But I'm facing the same problem again. Is it possible to fix?
![screen](https://cloud.githubusercontent.com/assets/6048978/17920440/29f580c6-69f2-11e6-9b2d-dad8ba3783ff.png)

**Comment by NSCabezon** [comment]
Did you check the lat and long of the two annotations? That may occur when you have two annotations that are really close to each other.

**Comment by palash89** [comment]
Yes, That's the main problem. I want to show annotations also for those whose coordinates are really close to each other.

**Comment by litoarias** [comment]
Temporary solution I can offer is to get all cluster indices has been pressed, with the following method:

-(void)didSelectAnnotationView:(HAClusterAnnotation *)annotationView
{
    NSLog(@"You ara select annotation index %ld", (long)annotationView.index);
    NSLog(@"%@", annotationView.indexes);
}
