### ISSUE TITLE
Memory leak detected in buildTreeWithArray function

### ISSUE THREAD

**Issue by Lapinou42** [litoarias/HACClusterMapViewController#2]
Hello, 

First of all, a big thank you to you for this lib ! 

I've noticed a memory leak in the function **buildTreeWithArray** in **HACManagerQuadTree.m**:

![capture d ecran 2015-12-03 a 11 27 35](https://cloud.githubusercontent.com/assets/3692744/11558129/11f4fbee-99b1-11e5-99a7-2d7d46ec415f.png)
![capture d ecran 2015-12-03 a 11 27 46](https://cloud.githubusercontent.com/assets/3692744/11558130/151c6b4a-99b1-11e5-9f5b-00e128497d6a.png)

I made these changes and no memory leak anymore.
It's the same thing for the function **buildTreeWithExample**

I simply added this:

``` objective-c
free(dataArray);
dataArray = NULL;
```

and change the function malloc to **calloc** (not necessary but useful in our case, no need to multiply explicitly).
![capture d ecran 2015-12-03 a 11 28 47](https://cloud.githubusercontent.com/assets/3692744/11558133/17d40636-99b1-11e5-8776-f9a243e7468a.png)

**Comment by litoarias** [comment]
Hello @Lapinou42 , thank you very much for your input .. The repo has now been updated with your contribution, the Pod will update soon .. Greetings :D
