### ISSUE TITLE
Please update podspec to proper version, still pointing to 2.4 instead of 2.6.2

### ISSUE THREAD

**Issue by Oggerschummer** [litoarias/HACClusterMapViewController#21]
The podspec file is still pointing to 2.4 instead of 2.6.2
This causes irritations when adding the pod into local project. regarding versioning.

**Comment by litoarias** [comment]
Hi @Oggerschummer,

You have new release pointing to 2.7, newest version..

Enjoy!

**Comment by Oggerschummer** [comment]
Hello @litoarias , it works like a charm, thanks for the quick response.
Greetings from Frankfurt.
