### ISSUE TITLE
Cluster issue

### ISSUE THREAD

**Issue by phaneendrakv** [litoarias/HACClusterMapViewController#7]
Individual pins are not showing up when the coordinates are too near adn zoomed in to maximum level, instead showing cluster count 

Sample Data:
 @{kLatitude:@48.47352, kLongitude:@3.87426,  kTitle : @"Title 1", kSubtitle : @"",            kIndex : @0},
                      @{kLatitude:@52.59758, kLongitude:@-1.93061, kTitle : @"Title 2", kSubtitle : @"Subtitle 2",  kIndex : @1},
                      @{kLatitude:@48.47352, kLongitude:@3.87425,  kTitle : @"Title 3", kSubtitle : @"Subtitle 3",  kIndex : @2},
                      @{kLatitude:@48.31921, kLongitude:@18.10184, kTitle : @"Title 4", kSubtitle : @"Subtitle 4",  kIndex : @3},
                      @{kLatitude:@47.84302, kLongitude:@22.81101, kTitle : @"Title 5", kSubtitle : @"Subtitle 5",  kIndex : @4},
                      @{kLatitude:@60.88622, kLongitude:@26.83792, kTitle : @"Title 6", kSubtitle : @""          ,  kIndex : @5}
                      ];
![screen shot 2016-01-13 at 1 17 44 pm](https://cloud.githubusercontent.com/assets/6537110/12288206/19438746-b9f8-11e5-8185-1ebf222ca63e.png)

**Comment by litoarias** [comment]
The spacing between pins is impossible is divided into two, they are literally together.
I'll see what I can do when I have time! excuse me
